#!/usr/bin/env python3
"""Sync gcgo with caPy's wire definitions (caPy's doc/csv).

caPy publishes what it puts on the wire as CSV: error and alarm codes, machine
states, status-report fields. This reads those files and

  * regenerates gcgo/core/codes.py (code -> text, used by the terminal) and
    gcgo/frontends/web/static/codes.json (the same, for the browser console);
  * checks that every machine state and status-report field caPy can send is
    one gcgo handles, and exits non-zero naming any it doesn't — that is the
    list of things to go and implement.

Run it after pulling caPy, then review `git diff`:

    python3 tools/sync_capy.py                  # ../caPy/doc/csv
    python3 tools/sync_capy.py path/to/doc/csv
"""
import csv
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from gcgo.core.protocol import _MOVING_STATES  # noqa: E402
from gcgo.core.tables import GRBL_ERRORS  # noqa: E402

# Machine states gcgo treats as settled (no motion left to wait for at the end
# of a job); everything else must be in protocol._MOVING_STATES.
SETTLED_STATES = ("Idle", "Alarm", "Check", "Sleep")
# Status-report fields GRBLStatus.update() parses, and ones it knowingly skips.
PARSED_FIELDS = ("State", "MPos", "WPos", "WCO", "FS", "Ov", "Pn")
IGNORED_FIELDS = ("Bf", "A")


def rows(src, name):
    with open(os.path.join(src, name), newline="", encoding="utf-8") as f:
        return list(csv.reader(f))[1:]


def capy_rev(src):
    try:
        return subprocess.check_output(
            ["git", "-C", src, "log", "-1", "--format=%h %ad", "--date=short"],
            text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def table(name, d):
    out = ["%s = {" % name]
    for k in sorted(d):
        out.append("    %d: %r," % (k, d[k]))
    out.append("}")
    return "\n".join(out)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "..", "caPy", "doc", "csv")
    if not os.path.isdir(src):
        sys.exit("no such directory: %s" % src)

    errors = {int(r[0]): r[2] for r in rows(src, "error_codes_en_US.csv")}
    alarms = {int(r[0]): r[2] for r in rows(src, "alarm_codes_en_US.csv")}
    states = [r[0] for r in rows(src, "machine_states_en_US.csv")]
    fields = [r[0] for r in rows(src, "status_report_en_US.csv")]

    # caPy's file carries GRBL's numbers too; keep gcgo's text for the GRBL
    # codes caPy never sends, so one table serves both controllers.
    merged = dict(GRBL_ERRORS)
    merged.update(errors)

    rev = capy_rev(src)
    with open(os.path.join(ROOT, "gcgo", "core", "codes.py"), "w", encoding="utf-8") as f:
        f.write('"""Error and alarm code text. GENERATED by tools/sync_capy.py from caPy\'s\n'
                'doc/csv (caPy %s) — do not edit; re-run the tool instead.\n\n'
                'Desktop only: the text is too large to load on a MicroPython board, where\n'
                'the browser reads the same tables from static/codes.json.\n"""\n\n' % rev)
        f.write(table("ERRORS", merged) + "\n\n" + table("ALARMS", alarms) + "\n")
    with open(os.path.join(ROOT, "gcgo", "frontends", "web", "static", "codes.json"),
              "w", encoding="utf-8") as f:
        json.dump({"errors": {str(k): merged[k] for k in sorted(merged)},
                   "alarms": {str(k): alarms[k] for k in sorted(alarms)}},
                  f, ensure_ascii=False, separators=(",", ":"))
        f.write("\n")
    print("caPy %s: %d error codes (%d caPy, %d GRBL-only), %d alarm codes"
          % (rev, len(merged), len(errors), len(merged) - len(errors), len(alarms)))

    unknown = []
    for s in states:
        base = s.split(":", 1)[0]
        if base not in _MOVING_STATES and base not in SETTLED_STATES:
            unknown.append("machine state %r" % s)
    for fld in fields:
        if fld not in PARSED_FIELDS and fld not in IGNORED_FIELDS:
            unknown.append("status-report field %r" % fld)
    if unknown:
        print("NOT HANDLED by gcgo:")
        for u in unknown:
            print("  " + u)
        sys.exit(1)
    print("all %d machine states and %d status-report fields are handled"
          % (len(states), len(fields)))


if __name__ == "__main__":
    main()
